version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s 