version: '3.8'

# Development configuration without nginx proxy
# Use this if you're having issues with large file uploads

services:
  web:
    build: .
    ports:
      - "8082:8082"  # Direct access to Flask app
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
  
  telegram-bot:
    build: .
    command: python telegram_bot_server.py
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./temp_files:/app/temp_files
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - web