version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${WEB_PORT:-8082}:80"
    restart: always
    volumes:
      - ./nginx-full.conf:/etc/nginx/nginx.conf:ro
      - nginx_upload_temp:/tmp/nginx_upload
      - ./temp_resources:/app/temp_resources
    depends_on:
      - web
    networks:
      - transcribe-network
    
  web:
    build: .
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - transcribe-network
  
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=1
      - TELEGRAM_API_DATA_DIR=${TELEGRAM_API_DATA_DIR:-/var/lib/telegram-bot-api}
    volumes:
      - telegram_bot_api_data:${TELEGRAM_API_DATA_DIR:-/var/lib/telegram-bot-api}
      - telegram_bot_api_temp:/var/tmp/telegram-bot-api
    ports:
      - "8081:8081"
    command: 
      - "--api-id=${TELEGRAM_API_ID}"
      - "--api-hash=${TELEGRAM_API_HASH}"
      - "--local"
      - "--dir=${TELEGRAM_API_DATA_DIR:-/var/lib/telegram-bot-api}"
      - "--temp-dir=/var/tmp/telegram-bot-api"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/bot${TELEGRAM_BOT_TOKEN}/getMe"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - transcribe-network
  
  telegram-bot:
    build: .
    command: sh -c "sleep 10 && python telegram_bot_server.py"
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./temp_files:/app/temp_files
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
      - telegram_bot_api_data:${TELEGRAM_API_MOUNT_PATH:-/telegram-bot-api-files}:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_API_URL=http://telegram-bot-api:8081/bot
      - TELEGRAM_API_DATA_DIR=${TELEGRAM_API_DATA_DIR:-/var/lib/telegram-bot-api}
      - TELEGRAM_API_MOUNT_PATH=${TELEGRAM_API_MOUNT_PATH:-/telegram-bot-api-files}
    depends_on:
      web:
        condition: service_started
      telegram-bot-api:
        condition: service_started
    networks:
      - transcribe-network

volumes:
  nginx_upload_temp:
  telegram_bot_api_data:
  telegram_bot_api_temp:

networks:
  transcribe-network:
    driver: bridge 