version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_upload_temp:/tmp/nginx_upload
      - ./temp_resources:/app/temp_resources
    depends_on:
      - web
    networks:
      - transcribe-network
    
  web:
    build: .
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - transcribe-network
  
  telegram-bot:
    build: .
    command: python telegram_bot_server.py
    restart: always
    volumes:
      - ./temp_resources:/app/temp_resources
      - ./temp_files:/app/temp_files
      - ./whitelist.json:/app/whitelist.json:ro
      - ./system_prompt.txt:/app/system_prompt.txt:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - web
    networks:
      - transcribe-network

volumes:
  nginx_upload_temp:

networks:
  transcribe-network:
    driver: bridge 